# Generated by Django 4.2.13 on 2025-05-27 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('code', models.CharField(choices=[('A', '單元 A：副木理論與用途介紹'), ('B', '單元 B：材料工具認識'), ('C', '單元 C：製作步驟示範'), ('D', '單元 D：臨床案例分析')], max_length=1, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_test_completed', models.BooleanField(default=False)),
                ('pre_test_score', models.FloatField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SimulationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_clarity', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='影片清晰度 (1-5)')),
                ('rating_usefulness', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='內容實用性 (1-5)')),
                ('rating_overall', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='整體滿意度 (1-5)')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='其他建議或回饋')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('video', '教學影片'), ('text_graphic', '圖文教材')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content_url', models.URLField(blank=True, help_text='教學影片連結 (例如 YouTube)', null=True)),
                ('content_text', models.TextField(blank=True, help_text='圖文教材內容 (HTML 可用)', null=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='splint_app.unit')),
            ],
        ),
    ]
