# Generated by Django 4.2.13 on 2025-05-31 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splint_app', '0002_alter_learningresource_content_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulationfeedback',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='simulationfeedback',
            name='rating_clarity',
        ),
        migrations.RemoveField(
            model_name='simulationfeedback',
            name='rating_overall',
        ),
        migrations.RemoveField(
            model_name='simulationfeedback',
            name='rating_usefulness',
        ),
        migrations.AddField(
            model_name='simulationfeedback',
            name='assessment',
            field=models.IntegerField(blank=True, null=True, verbose_name='1. 評估與測量技能'),
        ),
        migrations.AddField(
            model_name='simulationfeedback',
            name='material',
            field=models.IntegerField(blank=True, null=True, verbose_name='2. 材料準備與處理'),
        ),
        migrations.AddField(
            model_name='simulationfeedback',
            name='molding',
            field=models.IntegerField(blank=True, null=True, verbose_name='3. 塑形與成型技巧'),
        ),
        migrations.AddField(
            model_name='simulationfeedback',
            name='positioning',
            field=models.IntegerField(blank=True, null=True, verbose_name='4. 關節位置擺位'),
        ),
        migrations.AddField(
            model_name='simulationfeedback',
            name='reflection_notes',
            field=models.TextField(blank=True, null=True, verbose_name='反思與改進筆記'),
        ),
        migrations.AddField(
            model_name='simulationfeedback',
            name='securing',
            field=models.IntegerField(blank=True, null=True, verbose_name='6. 固定與調整'),
        ),
        migrations.AddField(
            model_name='simulationfeedback',
            name='trimming',
            field=models.IntegerField(blank=True, null=True, verbose_name='5. 修剪與邊緣處理'),
        ),
    ]
